### ISSUE TITLE
[Farmer's Delight compat] Buddybeans not dropping from crops

### ISSUE THREAD

**Issue by Febilian** [wildcardgamez/BuddyCards#12]
Tested with nothing but Farmer's Delight and Buddycards installed; harvested a full field of crops, no beans.

Is there something I'm missing here? Is there a requirement for getting the beans other than having the mods installed? I didn't notice anything about that in the patchouli guide.

`Forge 36.1.4`
`Buddycards 2.2.3`
`Farmer's Delight 0.4.1`

**Comment by wildcardgamez** [comment]
Not 100% sure if this is an actual issue. It is a 1/500 chance iirc, I'll ask some people who I know play it have ever found them

**Comment by BookerCatch** [comment]
This is the relevant snippet from the console log upon loading a world. It appears to be a malformed JSON issue 

https://pastebin.com/pu9JrXq9

**Comment by wildcardgamez** [comment]
ah thanks, ill look into it. It'll be fixed in the next patch

**Comment by BookerCatch** [comment]
I tried fixing the issue myself by overwriting the loot_modifiers file with a custom one. I believe the problem lies in lines 5-8 where the forge:mod_loaded condition is defined. Since it is contained within the "conditions" tag array, it expects to have a "condition" tag like all the other tags after it. 

![image](https://user-images.githubusercontent.com/43504436/115794767-93831880-a39c-11eb-9045-e396a9a0676f.png)

I could very well be wrong on this, but eliminating the forge:mod_loaded condition fixed the issue for me. I already have farmer's delight included in my modpack so the tag isn't necessary, but obviously you should have some way to include the condition in for when farmer's delight isn't present. There's probably some syntax rule I'm not familiar with.

**Comment by wildcardgamez** [comment]
Yeah, I gotta swap it from type to condition, also removing that block will cause issues when fd isn't loaded. Been busy with on of my other mods so i haven't had a chance to look at it.

**Comment by BookerCatch** [comment]
I also tried replacing the tag from type to condition, but I still received a syntax error. There may have been something else I did wrong, but I thought the tag just had to read "type".

**Comment by wildcardgamez** [comment]
Fixed
https://github.com/wildcardgamez/BuddyCards/commit/600932cd682968639a60e99c78fb6117476dfdde
